sudo: required

language: python
python: 3.6

services:
  - docker

script: /bin/true

deploy:
  - provider: script
    skip_cleanup: true
    script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make TAG="$TRAVIS_TAG" docker-push
    on:
      tags: true
