sudo: required
dist: bionic

language: python
python: 3.9

services:
  - docker

before_script:
- pip install black

script:
- find -name '*.py' | xargs black --target-version=py39 --check --diff

deploy:
  - provider: script
    skip_cleanup: true
    script: ./docker-push
    on:
      tags: true
