sudo: required

language: python
python: 3.6

services:
  - docker
  
before_script:
- pip install black
script:
- find -name '*.py' | xargs black --target-version=py36 --check --diff
- /bin/true

deploy:
  - provider: script
    skip_cleanup: true
    script: ./docker-push
    on:
      tags: true
